name: Build

on:
  push:
    branches-ignore:
      - 'release'

jobs:
  call-common-workflow:
    uses: ./.github/workflows/build-common.yml
    with:
      platform: ${{ matrix.platform }}
      args: ${{ matrix.args }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

  build:
    runs-on: ${{ matrix.platform }}
    needs: call-common-workflow
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    steps:
      - name: Call Common Build Steps
        uses: ./.github/workflows/build-common.yml
        with:
          platform: ${{ matrix.platform }}
          args: ${{ matrix.args }}

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}
